### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by Goddard** [RedSoftwareSystems/easy_docker_containers#21]
When I used this extension Gnome Shell ends up taking Gigs of ram.  I think it has a memory leak.

**Comment by kiuma** [comment]
Hi, I in Red we don't experience this problem, can you share details please ? 
Did you experience this memory leak also after a restart ?

**Comment by Goddard** [comment]
I'm on ubuntu 21.10 on X11.  Gnome version 40.4.0
