### ISSUE TITLE
JS error "fields are not currently supported" which blocks installation

### ISSUE THREAD

**Issue by Kupuyc** [RedSoftwareSystems/easy_docker_containers#31]
Good day.

There is error which blocks installation of the extension:
`Jun  4 22:53:03 host gnome-shell[2155]: JS ERROR: Extension easy_docker_containers@red.software.systems: SyntaxError: fields are not currently supported @ /home/host/.local/share/gnome-shell/extensions/easy_docker_containers@red.software.systems/src/dockerMenu.js:19`

It can be fixed by remove of line and move init of field into DockerMenu::_init():
```
_init(menuAlignment, nameText) {
  super._init(menuAlignment, nameText);
  this._containers = null;
```

Also, there is PR that tried to fix problem - [fix dockerMenu.js #14](https://github.com/RedSoftwareSystems/easy_docker_containers/pull/14).

- Gnome: 3.36.8
- OS: Ubuntu 20.04.4 LTS 64-bit
- GJS: 1.64.5

**Comment by kiuma** [comment]
Gnome version?

**Comment by Kupuyc** [comment]
> Gnome version?

3.36.8

**Comment by Kupuyc** [comment]
It works perfect after implement of PR #32 and update to fresh version. Thank you!

**Comment by kiuma** [comment]
Thanks for your review

Il mar 7 giu 2022, 06:20 Kupuyc ***@***.***> ha scritto:
