### ISSUE TITLE
System stuttering issue

### ISSUE THREAD

**Issue by Barben360** [RedSoftwareSystems/easy_docker_containers#33]
There are real performance issues with the extension. When it is activated, I have freezes every few seconds, which makes my system quite frustrating to use (especially when watching a video).

It disappears instantly as soon as the extension is disabled.

I use a Dell XPS 13 9360 with i7-8550u in performance mode, 16 GB RAM, with Ubuntu 22.04 on Wayland.

**Comment by kiuma** [comment]
Thank you for reporting. I need to investigate because we are not facing this issue on our pc. I'll let you know when I have any update

**Comment by Flavelius** [comment]
I have the same issue, and it happens at the refresh interval. If i unload the extension the interval-stutter is gone for me as well.
I don't remember this happening when i still had an nvidia gpu though. I think it began happening when i replaced it with an amd card. Not 100% sure though, might have just been coincidence or me misremembering.

**Comment by kiuma** [comment]
I don't understand how gpu could be related to this, but you could try with journalctl to better see what's happening under the hood

**Comment by Flavelius** [comment]
with journalctl -f i see these lines popping up every 2 seconds (update frequency):
 systemd[2351]: Started snap.docker.docker-[random guid-like number].scope.

docker is installed via snap on my system (ubuntu 24.04)
