### ISSUE TITLE
Support GNOME 45

### ISSUE THREAD

**Issue by HenriqueAmrl** [RedSoftwareSystems/easy_docker_containers#44]
GNOME Shell 45 includes changes which are incompatible with all existing GNOME shell extensions.

More informations:
- https://release.gnome.org/45/developers/index.html
- https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by hhoao** [comment]
https://github.com/RedSoftwareSystems/easy_docker_containers/pull/46
